### ISSUE TITLE
Issues with 18-053r2

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-samples-ogc#20]
Issues to be handled in markup or metanorma-ogc:

- Unnumbered tables are shown in the list of tables (I'm not sure if this is fine, since they are untitled).
- Chapters order is different (for the first 3 chapters).
- [class=steps] is not working.
- There's no option such as [source,json], so I've used [source,ruby].
- Warning on the front page has a different content, as well as the License Agreement.
- Front page is slightly different.
- There should be no "Open Geospatial Consortium 18-053r2:2020" in the header, and the footer should be different.
- In Terms and Definitions section, subsection titles are written below the corresponding number of the subsection, instead in the same line.
- Annex B should have the subtitle "non-normative". I'm not sure how to produce this, because obligation attribute should be informative or normative (?).
- Normative references aren't rendering and I didn't manage to figure out why.

**Comment by anermina** [comment]
Regarding my last comment (Normative references aren't rendering), this happens because there is a section "References" and then subsection "Normative", which is unusual. I propose to delete subsection "Normative", because [bibliography] with "References" renders as "Normative references" anyway. Pull request #45 was created for this change.

**Comment by opoudjis** [comment]
Issues conflated with https://github.com/metanorma/mn-samples-ogc/issues/21

> Unnumbered tables are shown in the list of tables (I'm not sure if this is fine, since they are untitled).

You mean figures, and untitled figures (because they are untitled sourcecode) are now being excluded from the list of tables. You may need to make them unnumbered.

> Chapters order is different (for the first 3 chapters).

The chapter order is correct

> [class=steps] is not working.

**Comment by opoudjis** [comment]
> There's no option such as [source,json], so I've used [source,ruby].

Use [source,javascript]: JSON is Javascript.

> Front page is slightly different.

Please be explicit as to how, given that things have been rearranged.  The only significant change I see is

> Please refer to the errata for this document, which may include some normative corrections.

Since the errata linked to from https://docs.opengeospatial.org/cs/18-053r2/18-053r2.html is in fact empty, I don't know whether there's anything for us to do here.

Oh, and the version number: add `:edition: 1.0` to this document header.

**Comment by opoudjis** [comment]
> In Terms and Definitions section, subsection titles are written below the corresponding number of the subsection, instead in the same line.

Fixing for Word

**Comment by opoudjis** [comment]
> Annex B should have the subtitle "non-normative". I'm not sure how to produce this, because obligation attribute should be informative or normative (?).

That is an inconsistency within OGC, since other standards, e.g. http://docs.opengeospatial.org/is/15-001r4/15-001r4.html#_annex_c_tiling_in_scene_based_3d_portrayal_informative, do refer to "informative". @ronaldtse Please escalate, we will impose uniform wording unless there are clear rules not to.

Confirmed in https://github.com/metanorma/metanorma-ogc/issues/94

**Comment by opoudjis** [comment]
@anermina 

> Normative references aren't rendering and I didn't manage to figure out why.

The proper fix to these, https://www.metanorma.com/author/topics/document-format/bibliography/#general , is:

````
== References

[bibliography]
=== Normative

````

**Comment by opoudjis** [comment]
Putting on hold, pending feedback from OGC

**Comment by anermina** [comment]
> You mean figures, and untitled figures (because they are untitled sourcecode) are now being excluded from the list of tables. You may need to make them unnumbered.

There are no these issues anymore. I've made the sourcecode unnumbered in #47 .

> The chapter order is correct

I believe you're right, since we first write Preface, then [.preface] sections. Currently, the original document has the following order:
1. Source of the content for this OGC document
2. Validity of content
3. Preface
4. Future work

On the other hand, generated document has the following order:
1. Preface
2. Source of the content for this OGC document
3. Validity of content
4. Future work

Comparison is shown in the following image (original is on the left, generated is on the right):
![image](https://user-images.githubusercontent.com/55683568/75823496-267c8000-5da2-11ea-86e5-380931f497c9.png)

> Use [source,javascript]: JSON is Javascript.

I'm familiar that JSON is Javascript, but I didn't know that [source,javascript] can be used, since it isn't written as an option on asciidoctor.org. Thanks, Nick! This is added as a change in #47, along with [%unnumbered] elements.

> Please be explicit as to how, given that things have been rearranged. The only significant change I see is (...)

Differences in the content on the front page are as follows:

- Title contains an extra word "OGC" in the generated document

Original:
 > 3D Tiles Specification 1.0

Generated:
 > OGC 3D Tiles Specification 1.0

- Before the warning, there is an extra line in the generated document:
 > To obtain additional rights of use, visit http://www.opengeospatial.org/legal/

- Warning content differs (original is on the left, generated is on the right):
![image](https://user-images.githubusercontent.com/55683568/75820088-08138600-5d9c-11ea-9ec6-b2475d10e0bc.png)

- Following elements are added at the bottom of the page in the original document, while they're not produced in the generated doc:
 > Document number: 18-053r2
 > Document subtype:

- Document language is rendered as "en" in the generated document.

Original:
 > Document language: English

Generated:
 > Document language: en

- Document stage differs (I've set :status: published in .adoc due to the available possibilities)

Original:
> Document stage: Approved

Generated: 
> Document stage: Published

> Oh, and the version number: add :edition: 1.0 to this document header.

Yes, this was already added in the commit #44 , and will be solved when it is merged.

> The proper fix to these, https://www.metanorma.com/author/topics/document-format/bibliography/#general , is: (...)

Regarding the references, I've added the correction in #45. This was already tried before, but as a result, I didn't get any references rendered. However, now it produces the expected output.

**Comment by opoudjis** [comment]
Remaining issues:

* License boilerplate: https://github.com/metanorma/metanorma-ogc/issues/91
* Treatment of errata, and other discrepancies with front page: @anermina @ronaldtse

**Comment by opoudjis** [comment]
The license boilerplate has been addressed: metanorma/metanorma-ogc#91

**Comment by opoudjis** [comment]
Reminder on remaining issues: @anermina @ronaldtse 

>> Front page is slightly different.


>> Please refer to the errata for this document, which may include some normative corrections.
> Since the errata linked to from https://docs.opengeospatial.org/cs/18-053r2/18-053r2.html is in fact empty, I don't know whether there's anything for us to do here.

**Comment by ronaldtse** [comment]
Ping @anermina , can you please help confirm here? Thanks.

**Comment by anermina** [comment]
@opoudjis , I can still see the differences written in my previous comment, when comparing generated DOC and PDF linked from https://docs.opengeospatial.org/cs/18-053r2/18-053r2.html.  Original PDF doesn't contain the following sentence: "Please refer to the errata for this document, which may include some normative corrections." - it is written only in HTML version of this document, so I believe we don't need to consider it. 



> Differences in the content on the front page are as follows:
> 
> * Title contains an extra word "OGC" in the generated document
> 
> Original:
> 
> > 3D Tiles Specification 1.0
> 
> Generated:
> 
> > OGC 3D Tiles Specification 1.0


> * Before the warning, there is an extra line in the generated document:
> 
> > To obtain additional rights of use, visit http://www.opengeospatial.org/legal/

Additionally, I've noticed this line also exists in the original HTML (but not in the original DOC and PDF), so this is an inconsistency in the original files.

> 
> * Warning content differs (original is on the left, generated is on the right):
>   ![image](https://user-images.githubusercontent.com/55683568/75820088-08138600-5d9c-11ea-9ec6-b2475d10e0bc.png)
> * Following elements are added at the bottom of the page in the original document, while they're not produced in the generated doc:
> 
> > Document number: 18-053r2
> > Document subtype:
> 
> * Document language is rendered as "en" in the generated document.
> 
> Original:
> 
> > Document language: English
> 
> Generated:
> 
> > Document language: en
> 
> * Document stage differs (I've set :status: published in .adoc due to the available possibilities)
> 
> Original:
> 
> > Document stage: Approved
> 
> Generated:
> 
> > Document stage: Published

**Comment by opoudjis** [comment]
> Title contains an extra word "OGC" in the generated document

This applies to Word and not to HTML. Removing OGC prefix from Word.

> Before the warning, there is an extra line in the generated document:
>>To obtain additional rights of use, visit http://www.opengeospatial.org/legal/

That line is part of the accepted copyright boilerplate for OGC. It stays.

> Additionally, I've noticed this line also exists in the original HTML (but not in the original DOC and PDF), so this is an inconsistency in the original files.

This is also part of the boilerplate phrasing, which we have now finalised with OGC; we are not going to reverse engineer previous versions of the boilerplate.

> Following elements are added at the bottom of the page in the original document, while they're not produced in the generated doc:
>> Document number: 18-053r2
>> Document subtype:

For them to have been missing in the Word template, they were missing in whatever I copied it from. Adding. The subtype was being omitted if empty; putting it back in.

> Document language is rendered as "en" in the generated document

Fixed in Word, correct in HTML.

> Document stage differs (I've set :status: published in .adoc due to the available possibilities)
> Original:
>> Document stage: Approved
> Generated:

>> Document stage: Published

We can only use the currently approved document stages; the standard is "published", not "approved".
